import SEO from '../components/SEO';
import { breadcrumbSchema, faqSchema } from '../lib/schema';
import { PageHero } from '../components/Hero';
import { images } from '../data/site';
import { Container, SectionTitle } from '../components/ui';
import FAQAccordion from '../components/FAQ';
import { ApproachSection, CTASection, WhySection } from '../components/Sections';
import PageTransition from '../components/PageTransition';

const faq = [
  { question: 'What kind of studio is MiraStudio?', answer: 'MiraStudio is a creative, marketing, and digital growth studio that supports businesses with branding, websites, content, campaigns, and ongoing marketing support.' },
  { question: 'Is MiraStudio only a design studio?', answer: 'No. MiraStudio provides design, strategy, marketing, content production, website support, digital presence development, and monthly growth support.' },
  { question: 'What makes MiraStudio different?', answer: 'MiraStudio connects brand, marketing, content, and digital execution under one direction, helping businesses stay consistent across every touchpoint.' }
];
const audiences = ['Startup Founders','New Businesses','Growing Brands','Digital & E-commerce Brands','Businesses That Need Monthly Support','Businesses Without an Internal Creative Team'];

export default function About() {
  return <PageTransition><SEO title="About MiraStudio | Creative & Digital Growth Studio" description="Learn about MiraStudio, a creative, marketing, and digital growth studio helping brands become clearer, stronger, and more consistent." path="/about" schemas={[breadcrumbSchema([{name:'Home',path:'/'},{name:'About',path:'/about'}]), faqSchema(faq)]}/><PageHero eyebrow="About" title="We help brands become clearer, stronger, and more consistent." intro="MiraStudio was built for founders, startups, and businesses that need more than individual design tasks. We help brands build direction, identity, digital presence, content, and marketing systems that work together." image={images.interior} alt="Minimal interior in warm neutral tones reflecting MiraStudio editorial direction."/><section className="bg-cream py-20 sm:py-28"><Container><div className="grid gap-5 lg:grid-cols-2"><Panel title="Our Belief" body="A strong brand does not happen by accident. It needs direction, consistency, purpose, and a message people can understand and trust. Design is not only about how a brand looks. It is about how a brand works, communicates, and connects with its audience."/><Panel title="Our Role" body="We work as a creative and growth partner for businesses that need support across brand, marketing, content, and digital platforms. We can help you launch a brand, refresh an existing one, build a website, create campaigns, manage monthly content, support paid advertising, improve your digital presence, or develop the creative materials your business needs to grow."/></div></Container></section><section className="bg-ivory py-20 sm:py-28"><Container><SectionTitle eyebrow="Who we work with" title="For businesses that need a stronger system, not isolated tasks."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{audiences.map((audience, i) => <article key={audience} className="border border-line bg-cream p-7"><p className="text-xs uppercase tracking-[.22em] text-muted">{String(i+1).padStart(2,'0')}</p><h3 className="mt-12 text-3xl font-medium tracking-tightest">{audience}</h3><p className="mt-4 text-sm leading-7 text-graphite">MiraStudio supports this stage with brand direction, digital structure, content systems, campaigns, and the creative materials needed to appear professional and grow consistently.</p></article>)}</div></Container></section><ApproachSection/><WhySection/><FAQAccordion items={faq}/><CTASection title="Let’s build your brand with direction."/></PageTransition>
}
function Panel({ title, body }: { title: string; body: string }) { return <article className="border border-line bg-ivory p-8"><h2 className="text-4xl font-medium tracking-tightest">{title}</h2><p className="mt-5 text-base leading-8 text-graphite">{body}</p></article> }
