import SEO from '../components/SEO';
import { breadcrumbSchema, faqSchema } from '../lib/schema';
import { PageHero } from '../components/Hero';
import { images, site } from '../data/site';
import { Container } from '../components/ui';
import FAQAccordion from '../components/FAQ';
import PageTransition from '../components/PageTransition';

const faq = [
  { question: 'How do I start working with MiraStudio?', answer: 'Send an inquiry with your business needs, and MiraStudio will help define the right service, scope, and next step.' },
  { question: 'Can I request more than one service?', answer: 'Yes. Many projects combine branding, website, content, marketing, and monthly support.' },
  { question: 'Does MiraStudio offer custom packages?', answer: 'Yes. MiraStudio can shape custom scopes for businesses with specific goals, platforms, campaigns, or monthly needs.' }
];
const options = ['Brand development','Website or digital presence','Marketing and campaigns','Social media content','Monthly partnership','Content production','Startup launch','Brand refresh','Custom project'];
export default function Contact() {
  return <PageTransition><SEO title="Contact MiraStudio | Start Your Brand Journey" description="Contact MiraStudio for brand development, website design, marketing campaigns, content production, monthly support, or custom creative projects." path="/contact" schemas={[breadcrumbSchema([{name:'Home',path:'/'},{name:'Contact',path:'/contact'}]), faqSchema(faq)]}/><PageHero eyebrow="Contact" title="Let’s build your brand." intro="Whether you are launching something new, improving your current brand, building a website, planning campaigns, or looking for monthly creative and marketing support, MiraStudio can help you move with direction." image={images.desk} alt="Minimal creative workspace for starting a MiraStudio project."/><section className="bg-cream py-20 sm:py-28"><Container><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><aside className="rounded-[2rem] border border-line bg-ivory p-7 shadow-[0_18px_60px_rgba(17,17,17,0.04)]"><p className="text-xs uppercase tracking-[.22em] text-muted">Start a project</p><h2 className="mt-8 text-4xl font-medium tracking-tightest">Tell us what your business needs.</h2><p className="mt-5 text-sm leading-7 text-graphite">We will help shape the right approach across brand development, digital presence, marketing campaigns, content production, monthly partnership, or custom creative projects.</p><p className="mt-8 text-sm text-graphite">{site.email}</p></aside><form className="rounded-[2rem] border border-line bg-ivory p-6 shadow-[0_18px_60px_rgba(17,17,17,0.04)] sm:p-8" onSubmit={(e) => e.preventDefault()}><div className="grid gap-5 md:grid-cols-2"><Input label="Name"/><Input label="Email" type="email"/><Input label="Phone"/><Input label="Company / Brand Name"/><Input label="Website or Instagram, optional" className="md:col-span-2"/><label className="md:col-span-2"><span className="mb-2 block text-sm font-medium">What do you need support with?</span><select className="min-h-12 w-full rounded-2xl border border-line bg-cream px-4 text-sm outline-none transition focus:border-ink">{options.map(o => <option key={o}>{o}</option>)}</select></label><label className="md:col-span-2"><span className="mb-2 block text-sm font-medium">Project message</span><textarea rows={7} className="w-full rounded-2xl border border-line bg-cream p-4 text-sm outline-none transition focus:border-ink"/></label><Input label="Estimated timeline"/><Input label="Estimated budget, optional"/></div><button className="mt-7 min-h-12 rounded-full bg-ink px-6 text-sm font-medium text-cream transition hover:bg-black">Send Inquiry</button></form></div></Container></section><FAQAccordion items={faq}/></PageTransition>
}
function Input({ label, type = 'text', className = '' }: { label: string; type?: string; className?: string }) { return <label className={className}><span className="mb-2 block text-sm font-medium">{label}</span><input type={type} className="min-h-12 w-full rounded-2xl border border-line bg-cream px-4 text-sm outline-none transition focus:border-ink"/></label> }
