import { Link, Navigate, useParams } from 'react-router-dom';
import SEO from '../components/SEO';
import { breadcrumbSchema, faqSchema, serviceSchema } from '../lib/schema';
import { services } from '../data/site';
import { PageHero } from '../components/Hero';
import { ServiceDetailCard } from '../components/Cards';
import FAQAccordion from '../components/FAQ';
import { CTASection } from '../components/Sections';
import { Container, Eyebrow, SectionTitle } from '../components/ui';
import PageTransition from '../components/PageTransition';

export default function ServiceDetail() {
  const { slug } = useParams();
  const service = services.find(s => s.slug === slug);
  if (!service) return <Navigate to="/services" replace/>;
  const related = services.filter(s => s.slug !== service.slug).slice(0,3);
  return <PageTransition><SEO title={service.seoTitle} description={service.description} path={service.path} schemas={[breadcrumbSchema([{name:'Home',path:'/'},{name:'Services',path:'/services'},{name:service.title,path:service.path}]), serviceSchema(service), faqSchema(service.faq)]}/><PageHero eyebrow={service.title} title={service.h1} intro={service.intro} image={service.image} alt={service.imageAlt}/><section className="bg-cream py-20 sm:py-28"><Container><SectionTitle eyebrow="What this includes" title="Detailed service capabilities built around clarity and execution."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{service.details.map(item => <ServiceDetailCard key={item.title} title={item.title} body={item.body} Icon={item.icon}/>)}</div></Container></section><section className="bg-ink py-20 text-cream sm:py-28"><Container><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow light>Who this is for</Eyebrow><h2 className="mt-5 text-5xl font-medium tracking-tightest">Built for the right stage and need.</h2></div><p className="text-xl leading-9 text-cream/70">{service.whoFor}</p></div></Container></section><section className="bg-ivory py-20 sm:py-28"><Container><SectionTitle eyebrow="Related services" title="Connect this service with the next layer of growth."/><div className="mt-12 grid gap-4 lg:grid-cols-3">{related.map(r => <Link key={r.slug} to={r.path} className="group border border-line bg-cream p-7 transition hover:bg-white"><p className="text-xs uppercase tracking-[.22em] text-muted">{r.number}</p><h3 className="mt-16 text-3xl font-medium tracking-tightest">{r.title}</h3><p className="mt-4 text-sm leading-7 text-graphite">{r.description}</p></Link>)}</div></Container></section>{service.slug === 'monthly-partnership' && <Packages/>}<FAQAccordion items={service.faq}/><CTASection title={service.cta}/></PageTransition>
}
function Packages() { const packs = ['Starter Monthly Support','Growth Monthly Support','Full Monthly Partnership','Custom Monthly Partnership']; return <section className="bg-cream py-20 sm:py-28"><Container><SectionTitle eyebrow="Monthly packages" title="Flexible support without fixed public pricing."/><div className="mt-12 grid gap-4 lg:grid-cols-4">{packs.map((pack,i) => <article key={pack} className="border border-line bg-ivory p-7"><p className="text-xs uppercase tracking-[.22em] text-muted">Custom pricing</p><h3 className="mt-14 text-3xl font-medium tracking-tightest">{pack}</h3><p className="mt-5 text-sm leading-7 text-graphite">{i===0?'For businesses that need consistent creative support and a more professional monthly presence.':i===1?'For businesses that need stronger marketing activity, campaign planning, and more consistent visibility.':i===2?'For businesses that need a complete creative, marketing, content, and digital support team.':'For businesses with larger needs, multiple brands, locations, frequent campaigns, production, development, or specialized marketing requirements.'}</p></article>)}</div></Container></section> }
